version: '3.8'
services:

  sql:
    image: sql
    build:
      dockerfile: sql.Dockerfile
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    restart: always

  api:
    image: api
    build:
      dockerfile: api.Dockerfile
    environment:
      - SQL_HOST=sql
    restart: always

  frontend:
    image: frontend
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    environment:
      - API_HOST=api
    restart: always
