version: '3.8'
services:

  api:
    image: api
    build:
      dockerfile: api.Dockerfile
    ports:
      - "3000:3000"
    restart: always

  sql:
    image: sql
    build:
      dockerfile: sql.Dockerfile
    ports:
      - "3306:3306"
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    restart: always

  frontend:
    image: frontend
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    restart: always
