version: '3.8'
services:

  sql:
    image: sql
    build:
      dockerfile: sql.Dockerfile
    command: --sql-mode="NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./sql:/app
    restart: always

  api:
    image: api
    build:
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/app
    restart: always

  frontend:
    image: frontend
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    restart: always
